(deffacts startup 
    (pie apple)
    (pie banoffee)
    (pie blackberry) 
    (pie blueberry) 
    (pie buko) 
    (pie cherry)  
    (pie chess) 
    (pie cream) 
    (pie custard) 
    (pie fried) 
    (pie key lime) 
    (pie lemon meringue) 
    (pie mince) 
    (pie pecan)
    (pie pumpkin)
    (pie rhubarb)
    (pie shoofly)
    (pie strawberry)
    (pie sugar) 
    (pie sweet potato)
)